# Generated by Django 3.0 on 2019-12-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
