# Generated by Django 3.0 on 2019-12-12 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0003_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='pub_date',
            new_name='created_date',
        ),
    ]
