# Generated by Django 3.0 on 2019-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0004_auto_20191212_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='control_id',
        ),
        migrations.RemoveField(
            model_name='control',
            name='name',
        ),
        migrations.RemoveField(
            model_name='value',
            name='name',
        ),
        migrations.AddField(
            model_name='control',
            name='control_index',
            field=models.IntegerField(default=3, verbose_name='control index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='control_name',
            field=models.CharField(default='dummyctrl', max_length=200, verbose_name='control name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='value_name',
            field=models.CharField(default='0db', max_length=200, verbose_name='current value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='value_name',
            field=models.CharField(default='0db', max_length=200, verbose_name='value name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='value',
            name='value_index',
            field=models.IntegerField(verbose_name='value index'),
        ),
    ]
