# Generated by Django 3.0 on 2019-12-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0005_auto_20191212_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
