# Generated by Django 3.0 on 2019-12-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0006_auto_20191215_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='control',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='control',
            name='value_name',
        ),
        migrations.AddField(
            model_name='control',
            name='value_current',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tinymix.Value'),
            preserve_default=False,
        ),
    ]
