# Generated by Django 3.0 on 2019-12-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0007_auto_20191215_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='control_index',
            new_name='control_id',
        ),
    ]
