# Generated by Django 3.0 on 2019-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0008_auto_20191215_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value_index',
            field=models.IntegerField(verbose_name='value id'),
        ),
    ]
