# Generated by Django 3.0 on 2019-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0009_auto_20191215_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_id',
            field=models.IntegerField(verbose_name='control id'),
        ),
    ]
