# Generated by Django 3.0 on 2019-12-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0010_auto_20191215_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='value_index',
            new_name='value_id',
        ),
    ]
