# Generated by Django 3.0 on 2019-12-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0011_auto_20191215_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='device_id',
            field=models.IntegerField(default=0, verbose_name='device id'),
            preserve_default=False,
        ),
    ]
