# Generated by Django 3.0 on 2019-12-16 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0012_config_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='value_current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tinymix.Value'),
        ),
    ]
