# Generated by Django 3.0 on 2019-12-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0013_auto_20191216_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='value_dynamic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_dynamic', to='tinymix.Value'),
        ),
        migrations.AlterField(
            model_name='control',
            name='value_current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_current', to='tinymix.Value'),
        ),
    ]
