# Generated by Django 3.0 on 2019-12-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0014_auto_20191216_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='value_current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tinymix.Value'),
        ),
    ]
