# Generated by Django 3.0 on 2019-12-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0015_auto_20191216_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='value_dynamic',
            field=models.CharField(default=None, max_length=200, verbose_name='control name'),
        ),
    ]
