# Generated by Django 3.0 on 2019-12-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0018_auto_20191216_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='value_dynamic',
            new_name='value_readback',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='value_current',
            new_name='value_stored',
        ),
    ]
