# Generated by Django 3.0 on 2019-12-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0019_auto_20191216_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='control_type',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='type'),
        ),
    ]
