# Generated by Django 3.0 on 2019-12-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0020_control_control_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='int_value_max',
            field=models.IntegerField(default=-1, verbose_name='int value max'),
        ),
        migrations.AddField(
            model_name='value',
            name='int_value_min',
            field=models.IntegerField(default=-1, verbose_name='int value min'),
        ),
        migrations.AddField(
            model_name='value',
            name='values_number',
            field=models.IntegerField(default=1, verbose_name='values number'),
        ),
        migrations.AddField(
            model_name='value',
            name='values_type',
            field=models.CharField(default='ENUM', max_length=20, verbose_name='value name'),
        ),
    ]
