# Generated by Django 3.0 on 2019-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinymix', '0021_auto_20191216_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='int_value',
            field=models.CharField(default='', max_length=200, verbose_name='value name'),
        ),
    ]
